Update ssh-cipher-perf-test

diff --git a/ssh-cipher-perf-test b/ssh-cipher-perf-test
--- a/ssh-cipher-perf-test
+++ b/ssh-cipher-perf-test
@@ -16,9 +16,9 @@ benchmark-ssh-ciphers() {
 setup-temp-authorized-keys() {
     test -f ~/.ssh/authorized_keys && {
         mv ~/.ssh/authorized_keys ~/.ssh/authorized_keys.backup || {
-	    echo "Moving ~/.ssh/authorized_keys to ~/.ssh/authorized_keys.backup failed, aborting test."
-	    exit 1;
-	}
+	        echo "Moving ~/.ssh/authorized_keys to ~/.ssh/authorized_keys.backup failed, aborting test.";
+	        exit 1;
+	    }
     }
     cat ~/.ssh/*.pub > ~/.ssh/authorized_keys;
     chmod 400 ~/.ssh/authorized_keys;
@@ -27,7 +27,7 @@ setup-temp-authorized-keys() {
 restore-orig-authorized-keys() {
     test -f ~/.ssh/authorized_keys.backup && {
         rm -f ~/.ssh/authorized_keys;
-	mv ~/.ssh/authorized_keys.backup ~/.ssh/authorized_keys;
+	    mv ~/.ssh/authorized_keys.backup ~/.ssh/authorized_keys;
     }
 }
 
@@ -40,7 +40,7 @@ exec-benchmark() {
 if [[ $(uname -s) == "Darwin" ]]; then
     if [[ $(sudo systemsetup -getremotelogin) =~ "Off" ]]; then
         sudo systemsetup -setremotelogin on;
-	echo "$(date +%s)" > ~/.ssh/remotelogin-enabled;
+	    echo "$(date +%s)" > ~/.ssh/remotelogin-enabled;
     fi
 fi
 
@@ -50,6 +50,6 @@ if [[ $(uname -s) == "Darwin" ]]; then
     test -f ~/.ssh/remotelogin-enabled && {
         sudo systemsetup -setremotelogin off && {
 	    rm ~/.ssh/remotelogin-enabled;
-	}
+	    }
     }
 fi
